title = "gitleaks config"

[[rules]]
    description = "AWS Manager ID"
    regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
    tags = ["key", "AWS"]
    [rules.allowlist]
        description = "ignore some aws keys"
        regex = '''(AKIAIOSFODNN7EXAMPLE|AKIAIO5FODNN7EXAMPLE|AKIA6HHRMQLJMDVXY6OR|AKIAIOSFODNN3EXAMPLE|AKIAIOSFODNS3EXAMPLE|AKIAIOSFOLAKEEXAMPLE|AKIAJ5SI5UWYOAXGHOXQ|AKIAJF2VSETNW3RTP3ZQ|AKIAJF4EV2DBC56IOAOQ|AKIAJIEMTME6UEVWXB2Q|AKIAJKKRUNSYM5MZSHDQ|AKIAJKLO4PDKEBQUDHYQ|AKIAJLQLVNL2XZ7EH6RQ|AKIAJNYOQZSWBSSXURPQ|AKIAJTZZYQTU5YGV4O3Q|AKIAJV3OAIYRIVODAQVQ|AKIAJVD5P3WTAFH7IN5Q|AKIAJXQPFV4FZH7UMMAQ|AKIAYRJJ6GNGCYQEPB7A).*'''

[allowlist]
    description = "Allowlisted files"
    files = [ '''^\.?gitleaks.toml$''', '''(.*?)(jpg|gif|doc|pdf|bin)$''', '''(go.mod|go.sum)$''']

