# Docker compose for local build and run of lakeFS.
# - use local blockstore
# - assume generated code step was executed (make gen)
#
# docker-compose up --build -d
#
version: '3'
services:
  lakefs:
    build: .
    ports: 
      - "8000:8000"
    depends_on:
      - "postgres"
    environment:
      - LAKEFS_BLOCKSTORE_TYPE=local
      - LAKEFS_AUTH_ENCRYPT_SECRET_KEY=some random secret string
      - LAKEFS_DATABASE_CONNECTION_STRING=postgres://lakefs:lakefs@postgres/postgres?sslmode=disable
      - LAKEFS_BLOCKSTORE_LOCAL_PATH=/home/lakefs
      - LAKEFS_GATEWAYS_S3_DOMAIN_NAME=s3.local.lakefs.io:8000
      - LAKEFS_STATS_ENABLED
      - LAKEFS_LOGGING_LEVEL
      - LAKEFS_CATALOGER_TYPE
      - LAKEFS_COMMITTED_LOCAL_CACHE_DIR
      - LAKEFS_COMMITTED_LOCAL_CACHE_SIZE_BYTES
      - LAKEFS_COMMITTED_SSTABLE_MEMORY_CACHE_SIZE_BYTES
      - LAKEFS_COMMITTED_LOCAL_CACHE_RANGE_PROPORTION
      - LAKEFS_COMMITTED_LOCAL_CACHE_RANGE_OPEN_READERS
      - LAKEFS_COMMITTED_LOCAL_CACHE_RANGE_NUM_SHARDS
      - LAKEFS_COMMITTED_LOCAL_CACHE_METARANGE_PROPORTION
      - LAKEFS_COMMITTED_LOCAL_CACHE_METARANGE_OPEN_READERS
      - LAKEFS_COMMITTED_LOCAL_CACHE_METARANGE_NUM_SHARDS
      - LAKEFS_COMMITTED_PERMANENT_MIN_RANGE_SIZE_BYTES
      - LAKEFS_COMMITTED_PERMANENT_MAX_RANGE_SIZE_BYTES
      - LAKEFS_COMMITTED_PERMANENT_RANGE_RAGGEDNESS_ENTRIES

    entrypoint: ["/app/wait-for", "postgres:5432", "--", "/app/lakefs", "run"]
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_USER: lakefs
      POSTGRES_PASSWORD: lakefs
