version: "3.5"
services:

  lakefs:
    image: treeverse/lakefs:latest
    pull_policy: always
    container_name: lakefs
    ports:
      - "8000:8000"
    environment:
      - LAKECTL_CREDENTIALS_ACCESS_KEY_ID=AKIA-EXAMPLE-KEY
      - LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY=EXAMPLE-SECRET
      - LAKECTL_SERVER_ENDPOINT_URL=http://localhost:8000
    volumes:
      - $PWD:/data
    entrypoint: ["/bin/sh", "-c"]
    command:
        - |
          lakefs setup --local-settings --user-name admin --access-key-id "$$LAKECTL_CREDENTIALS_ACCESS_KEY_ID" --secret-access-key "$$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY" || true
          lakefs run --local-settings &
          echo "---- Creating repository ----"
          wait-for -t 60 lakefs:8000 -- lakectl repo create lakefs://quickstart local://quickstart || true
          echo ""
          echo "---- Uploading sample data ----"
          lakectl fs upload lakefs://quickstart/main/lakes.parquet --source /data/lakes.parquet || true
          lakectl commit lakefs://quickstart/main -m "Load sample data" || true
          echo ""
          echo "---- Adding branch protection to main ----"
          echo "(changes can only be merged to main, not committed directly)"
          lakectl branch-protect add lakefs://quickstart main || true
          echo ""
          echo "-------- Let's go and have axolotl fun! --------"
          echo ""
          echo ">(.ï¼¿.)<     http://127.0.0.1:8000/      "
          echo "  (  )_"
          echo "             Access Key ID    : $$LAKECTL_CREDENTIALS_ACCESS_KEY_ID"
          echo "             Secret Access Key: $$LAKECTL_CREDENTIALS_SECRET_ACCESS_KEY"          
          echo ""
          echo "------------------------------------------------"
          wait

  duckdb:
    image: rmoff/duckdb
    container_name: duckdb
    entrypoint: 
      - /bin/sh 
      - -c 
      - |
        while [ 1 -eq 1 ];do sleep 60;done