# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

aux_links_new_tab: true

logo: '/assets/logo.svg'
logo_link: 'https://lakefs.io'

remote_theme: pmarsceill/just-the-docs



# Aux links for the upper right navigation
aux_links:
  'Docs':
    - 'https://docs.lakefs.io/'
  'Github':
    - 'https://github.com/treeverse/lakeFS'
  'Blog':
    - 'https://www.lakefs.io/blog'

buttons:
  'Get Started':
      - 'https://docs.lakefs.io/'

# FOOTER
# use "footer_content" for simple footer
# footer_content: 'Copyright &copy; 2020 Treeverse Labs LTD.'
footer:
  'img-bottom':
    - '/assets/by-treeverse.png'
  'img-bottom-link':
    - 'https://www.treeverse.io/'

footer_links:
  'Docs':
    - 'https://docs.lakefs.io/'
  'Github':
    - 'https://github.com/treeverse/lakeFS'
  'Blog':
    - 'https://www.lakefs.io/blog'
  'Contact':
    - 'https://lakefs.io/contact-us/'

footer_social:
  'linkedin':
    - 'https://www.linkedin.com/company/treeverse'
  'github':
    - 'https://github.com/treeverse/lakeFS'
  'twitter':
    - 'https://twitter.com/lakeFS'
  'slack':
    - 'https://join.slack.com/t/lakefs/shared_invite/zt-g86mkroy-186GzaxR4xOar1i1Us0bzw'

footer_bottom_links:
  'Terms of use':
    - 'https://lakefs.io/terms-of-use/'
  'Privacy Policy':
    - 'https://lakefs.io/privacy-policy/'
    
image: '/assets/img/shared-image.png'

plugins:
  - jekyll-redirect-from