remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

logo: "/assets/logo.png"

ga_tracking: UA-167126751-1

footer_content: "Copyright &copy; 2020 Treeverse Labs LTD."
