name: changelog

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
    paths-ignore:
      - 'docs/**'

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@a3c219da6b8fa73f6ba62b68ff09c469b3a1c024 #tag 2.2.2
        with:
          REQUIRED_LABELS_ANY: "include-changelog,exclude-changelog"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Enforcing that a PR must have one of (include-changelog,exclude-changelog) labels to be merged"
