name: hadoopFS
on:
  push:
    paths:
      - "clients/hadoopfs/**"
    branches:
      - master
  pull_request:
jobs:
  lakefs-hadoopfs:
    name: lakeFS hadoopFS
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build api client
        working-directory: clients/java
        run: mvn --batch-mode --update-snapshots install
      - name: Build hadoopfs
        working-directory: clients/hadoopfs
        run: mvn --batch-mode --update-snapshots verify
